/**
 * 从 lucide.min.js 提取指定图标数据，生成精简的映射表文件。
 *
 * 用法: node scripts/build-icons.js
 * 输出: lib/lucide-icons.js
 *
 * 需要提取的 Lucide 图标名称列表维护在下方 ICON_KEYS 中。
 * 面板可选图标及其自定义 key 的映射关系在 iconPicker.js 的 ICON_REGISTRY 中维护。
 */

const fs = require('fs');
const path = require('path');

const lucide = require(path.resolve(__dirname, '../lib/lucide.min.js'));

// 需要提取的 Lucide 图标（PascalCase key）
// 必须覆盖 iconPicker.js ICON_REGISTRY 中所有引用的 Lucide key
const ICON_KEYS = [
    'Folder', 'Bookmark', 'Star', 'Heart', 'Flag', 'Tag',
    'Pin', 'Code', 'Terminal', 'Laptop', 'Smartphone',
    'Database', 'Cloud', 'Cpu', 'Briefcase', 'Building',
    'BarChart3', 'BookOpen', 'GraduationCap', 'Lightbulb',
    'Pencil', 'Newspaper', 'Rss', 'Mail', 'MessageCircle',
    'Phone', 'Users', 'Music', 'Camera', 'Film',
    'Video', 'Image', 'Headphones', 'Palette', 'Gamepad',
    'Home', 'ShoppingCart', 'Store', 'Wallet', 'CreditCard',
    'Package', 'Utensils', 'Coffee', 'Dumbbell', 'HeartPulse',
    'Plane', 'Globe', 'Car', 'MapPin', 'Compass',
    'Leaf', 'PawPrint', 'Wrench', 'Shield', 'Lock', 'Key',
    'Eye', 'Clock', 'Search', 'Link', 'Sparkles',
    'Zap', 'SmilePlus',
    'EllipsisVertical', 'FolderPlus', 'FolderInput', 'Trash2',
    'ExternalLink', 'X', 'ArrowUpDown', 'ChevronRight',
];

const result = {};
const missing = [];

for (const key of ICON_KEYS) {
    const data = lucide.icons[key];
    if (!data) {
        missing.push(key);
        continue;
    }
    result[key] = data;
}

if (missing.length) {
    console.error('Icons not found in lucide:', missing.join(', '));
    process.exit(1);
}

const lucideVersion = (() => {
    try {
        const src = fs.readFileSync(
            path.resolve(__dirname, '../lib/lucide.min.js'), 'utf-8'
        );
        const m = src.match(/@license lucide v([\d.]+)/);
        return m ? m[1] : 'unknown';
    } catch { return 'unknown'; }
})();

const output = [
    `// Auto-generated by scripts/build-icons.js — DO NOT EDIT`,
    `// Source: lucide v${lucideVersion} | Generated: ${new Date().toISOString()}`,
    `// Icons: ${ICON_KEYS.length}`,
    `//`,
    `// Lucide License: ISC (https://github.com/lucide-icons/lucide/blob/main/LICENSE)`,
    `// Format: { LucideKey: [[tagName, {attrs}], ...], ... }`,
    ``,
    `const LUCIDE_ICONS = ${JSON.stringify(result)};`,
    ``,
].join('\n');

const outPath = path.resolve(__dirname, '../lib/lucide-icons.js');
fs.writeFileSync(outPath, output, 'utf-8');

const sizeKB = (Buffer.byteLength(output, 'utf-8') / 1024).toFixed(1);
console.log(`Generated ${outPath}`);
console.log(`  Icons: ${ICON_KEYS.length} | Size: ${sizeKB} KB | Lucide: v${lucideVersion}`);
